services:
  db:
    container_name: snake-backend-db
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snake_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql@15/data

  app:
    container_name: snake-backend-app
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=snake_db
      - DB_PORT=5432
      - DB_HOST=snake-backend-db
    pids_limit: 500
    mem_limit: 1G
    cpus: 2
    ports:
      - 8080:9000

volumes:
  pgdata: